### PR TITLE
Feature/file structure

### LINKED ISSUE #9: Create a file structure
Create an appropriate file structure for the application. 
File structure to contain an assets folder to accomodate the css and js files.

### PR DESCRIPTION
**Pull request by Cbeattie97**
basic file structure to build upon.

### CODE REVIEW

**Review by kevinvongmany — CHANGES_REQUESTED** [review]
Looks good so far, could you:

1. Delete `assets/styles.css` (we only need 1)
2. Import the files into the HTML code

Thanks!

**Comment by Cbeattie97** [comment]
Thanks Kevin, I picked up on the additional CSS file and updated the request yesterday. 

As for the HTML file, I've created the index.html just to test run the GitHub workflow. I imagined adding code would be related to each issue and branch?

**Comment by Cbeattie97** [comment]
Assets files have been imported into the html now.

**Review by leontran44 — APPROVED** [review]
Looks good enough!

**Comment by kevinvongmany** [comment]
Good

**Review by kevinvongmany — APPROVED** [review]

**Pull request merged**
