### PR TITLE
Finished README.md

### PR DESCRIPTION
**Pull request by Cbeattie97**

### CODE REVIEW

**Review by leontran44 — CHANGES_REQUESTED** [review]
From Usage section downwards, the format become quote.

**Comment by Cbeattie97** [comment]
> From Usage section downwards, the format become quote.

Thanks Leon, Should work fine now

**Review by leontran44 — APPROVED** [review]
Looks better Cameron :D

**Review by kevinvongmany — APPROVED** [review]
Looks great!

**Pull request merged**
